//! [`AgentBlueprint`] — the contract between user-defined agent structs
//! (generated by the `agent-macros` crate) and the runtime assembler.

use engine::AgentHook;
use tools::ToolRegistry;

/// Describes a user-defined agent struct to the runtime.
///
/// The `#[derive(Agent)]` macro implements the *field* halves
/// ([`blueprint_system_prompt`](Self::blueprint_system_prompt),
/// [`blueprint_register_field_tools`](Self::blueprint_register_field_tools),
/// [`blueprint_context_hooks`](Self::blueprint_context_hooks));
/// the `#[agent_impl]` macro implements the *method* halves
/// ([`blueprint_register_method_tools`](Self::blueprint_register_method_tools)).
///
/// Because each macro implements a *different* method of the same trait,
/// the two can coexist without conflict — and omitting either macro
/// simply yields an empty implementation for that half.
///
/// The LLM client itself is **not** part of this trait: `LLMClient` is
/// implemented with native async fn (RPITIT), which is not dyn-compatible,
/// so the client is accessed through the derive-generated `into_agent`
/// methods with concrete types instead.
pub trait AgentBlueprint {
    /// The system prompt (from the struct's doc comment).
    fn blueprint_system_prompt(&self) -> String;

    /// Register **all** tools: struct fields first, then `#[agent_impl]` methods.
    fn blueprint_register_tools(&self, registry: &mut ToolRegistry) {
        self.blueprint_register_field_tools(registry);
        self.blueprint_register_method_tools(registry);
    }

    /// Register tools that are struct fields annotated `#[tool]`.
    /// Generated by `#[derive(Agent)]`; empty by default.
    fn blueprint_register_field_tools(&self, _registry: &mut ToolRegistry) {}

    /// Register tools generated from synchronous methods in a
    /// `#[agent_impl]` block. Generated by `#[agent_impl]`; empty by default.
    fn blueprint_register_method_tools(&self, _registry: &mut ToolRegistry) {}

    /// Names of all tools, for TUI status bars and `/tools` listings.
    fn blueprint_tool_names(&self) -> Vec<String> {
        let mut names = Vec::new();
        names.extend(self.blueprint_field_tool_names());
        names.extend(self.blueprint_method_tool_names());
        names
    }

    /// Tool names from struct fields. Generated by `#[derive(Agent)]`.
    fn blueprint_field_tool_names(&self) -> Vec<String> {
        Vec::new()
    }

    /// Tool names from `#[agent_impl]` methods. Generated by `#[agent_impl]`.
    fn blueprint_method_tool_names(&self) -> Vec<String> {
        Vec::new()
    }

    /// Context hooks (from `#[context(...)]` fields).
    /// Generated by `#[derive(Agent)]`; empty by default.
    fn blueprint_context_hooks(&self) -> Vec<Box<dyn AgentHook>> {
        Vec::new()
    }
}
