//! # Agent — Core ReAct Loop
//!
//! Drives autonomous tool-using conversations with an LLM provider.

use std::collections::BTreeMap;
use std::fmt;
use std::sync::Arc;
use std::time::Duration;

use futures_util::StreamExt;
use tokio::sync::mpsc;

use memory::SharedMemory;
use provider::{
    CompletionRequest, CompletionResponse, FinishReason, LLMClient, Message, ProviderError, Role,
    StreamChunk, ToolCall, ToolCallFunction, ToolCallKind,
};
use tools::{Progress, ToolError, ToolRegistry};

use crate::builder::AgentBuilder;
use crate::context::EngineContext;
use crate::hooks::AgentHook;

// ── AgentError ────────────────────────────────────────────────────────────────

#[derive(Debug)]
pub enum AgentError {
    Provider(ProviderError),
    Tool { name: String, error: ToolError },
    MaxStepsReached(usize),
    NoOutput,
    NoChoices,
    Memory(String),
    ToolRejected { name: String, reason: String },
    StreamTimeout,
}

impl fmt::Display for AgentError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Provider(e) => write!(f, "provider error: {e}"),
            Self::Tool { name, error } => write!(f, "tool '{name}' error: {error}"),
            Self::MaxStepsReached(n) => write!(f, "max steps ({n}) reached"),
            Self::NoOutput => write!(f, "model returned empty output"),
            Self::NoChoices => write!(f, "response has no choices"),
            Self::Memory(msg) => write!(f, "memory error: {msg}"),
            Self::ToolRejected { name, reason } => write!(f, "tool '{name}' rejected: {reason}"),
            Self::StreamTimeout => write!(f, "stream timed out — no data received from provider"),
        }
    }
}

impl std::error::Error for AgentError {}

impl From<ProviderError> for AgentError {
    fn from(e: ProviderError) -> Self {
        Self::Provider(e)
    }
}

// ── CallOrigin ────────────────────────────────────────────────────────────────

/// Distinguishes who initiated a tool or command invocation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CallOrigin {
    /// The LLM decided to invoke a tool.
    Llm,
    /// The user initiated this directly (e.g. `!git status` in a TUI).
    User,
}

// ── Intervene ─────────────────────────────────────────────────────────────────

/// A hook or sandbox component is asking the user to make a decision.
///
/// The application renders this as an interactive prompt.  The user picks
/// one of the [`options`](Self::options).  If the chosen option's label
/// ends with `…` (U+2026), the application opens a text-input dialog and
/// the free-form text is returned in [`InterventionResponse::custom_text`].
#[derive(Debug, Clone)]
pub struct InterventionRequest {
    /// Opaque id generated by the requester — echoed back in the response
    /// so the requester can correlate when multiple requests are in flight.
    pub request_id: String,
    /// Short question displayed prominently.
    /// e.g. `"Approve shell command?"`, `"Choose build system"`
    pub title: String,
    /// Detailed context — the shell command, a diff, conflicting paths, etc.
    pub description: String,
    /// One or more choices.  For simple confirmations use
    /// `["Approve", "Deny"]`.  An option whose label ends with `…`
    /// triggers free-form text input.
    pub options: Vec<String>,
}

/// The user's answer to an [`InterventionRequest`].
#[derive(Debug, Clone)]
pub struct InterventionResponse {
    /// Index into [`InterventionRequest::options`] that the user selected,
    /// or `None` if the user dismissed the prompt (Esc / cancel).
    pub chosen: Option<usize>,
    /// Free-form text when the user selected a `…`-suffixed option
    /// and typed a custom answer.
    pub custom_text: Option<String>,
}

// ── RunOutcome ────────────────────────────────────────────────────────────────

/// Describes how an agent run terminated.
///
/// Passed to [`AgentHook::on_run_finish`](crate::AgentHook::on_run_finish) so
/// hooks can distinguish success, error, and cancellation.
#[derive(Debug, Clone)]
pub enum RunOutcome {
    /// Agent completed successfully with the final answer text.
    Success {
        /// The final assistant text returned to the caller.
        answer: String,
    },
    /// Agent terminated with an error (provider, tool, max-steps, etc.).
    Error {
        /// Human-readable error message from [`AgentError::to_string`].
        error: String,
    },
    /// The user cancelled the run (e.g. Ctrl+C in the TUI).
    Cancelled,
}

// ── AgentEvent ────────────────────────────────────────────────────────────────

/// Streaming events produced during an agent run.
///
/// Events flow from the agent loop to the application (e.g. a TUI) over a
/// single [`tokio::sync::mpsc::unbounded_channel`].  Every event type the
/// framework can produce is a variant of this enum — applications never
/// need to define their own custom event type.
#[derive(Debug, Clone)]
pub enum AgentEvent {
    /// An agent run has started — the TUI should enter "streaming" mode.
    RunStarted {
        /// Opaque session identifier (currently `"default"`).
        session_id: String,
        /// The user input that triggered this run.
        user_input: String,
    },
    /// A text token from the LLM response stream.
    Token(String),
    /// A reasoning / chain-of-thought token.
    ReasoningToken(String),
    /// A tool or user-command invocation, emitted before execution begins.
    /// Use [`origin`](CallOrigin) to distinguish LLM tool calls from
    /// user-initiated commands (e.g. `!git status`).
    ToolCall {
        id: String,
        name: String,
        arguments: String,
        /// Who initiated this call — the LLM or the user.
        origin: CallOrigin,
    },
    /// Tool execution completed successfully.
    ToolSuccessful {
        id: String,
        name: String,
        output: String,
    },
    /// A hook rejected the tool before it could execute (e.g. sandbox policy).
    ToolRejected {
        id: String,
        name: String,
        reason: String,
    },
    /// Tool execution failed — the tool returned an error or was not found.
    ToolFailure {
        id: String,
        name: String,
        error: String,
    },
    /// Real-time progress update from a running tool.
    ToolProgress {
        id: String,
        name: String,
        message: String,
    },
    /// A hook is requesting user intervention before proceeding.
    /// The application should render the request, collect an answer, and
    /// send back an [`InterventionResponse`] via the intervention channel.
    InterventionRequired(InterventionRequest),
    /// The agent completed the run successfully — carries the final answer.
    /// Emitted before [`Done`](AgentEvent::Done).
    RunCompleted {
        /// The final assistant text returned by the model.
        answer: String,
    },
    /// The agent run terminated with an error.
    /// Emitted before [`Done`](AgentEvent::Done).
    RunFailed {
        /// Human-readable error message.
        error: String,
    },
    /// The user cancelled the agent run (e.g. Ctrl+C).
    /// Emitted before [`Done`](AgentEvent::Done).
    Cancelled,
    /// The agent has finished the current run — reset streaming state.
    /// Always the final event, regardless of success, failure, or cancellation.
    Done,
}

// ── Agent ─────────────────────────────────────────────────────────────────────

pub struct Agent<C: LLMClient> {
    ctx: EngineContext<C>,
}

impl<C: LLMClient> Agent<C> {
    /// Create a new [`Agent`] from a fully-configured [`EngineContext`].
    ///
    /// This is the **advanced** entry point.  Most users should prefer
    /// [`Agent::builder`] which provides a fluent API with sensible defaults.
    pub fn new(ctx: EngineContext<C>) -> Self {
        Self { ctx }
    }

    /// Create an [`AgentBuilder`] with the two **required** dependencies.
    ///
    /// All other settings have sensible defaults:
    ///
    /// | Field | Default |
    /// |-------|---------|
    /// | `memory` | Auto-created empty [`Memory`] |
    /// | `tools` | Empty registry |
    /// | `hooks` | Empty |
    /// | `system_prompt` | `None` |
    /// | `max_steps` | `50` |
    /// | `max_retries` | `3` |
    /// | `streaming` | `true` |
    /// | Compaction | Off — opt in via `.with_micro_compact()` / `.with_macro_compact()` |
    ///
    /// # Example
    ///
    /// ```ignore
    /// let agent = Agent::builder(client, "deepseek-v4")
    ///     .system_prompt("You are a helpful assistant.")
    ///     .tool(calculator_tool)
    ///     .build();
    ///
    /// let answer = agent.run("2+2=?").await?;
    /// ```
    pub fn builder(llm: C, model: impl Into<String>) -> AgentBuilder<C> {
        AgentBuilder::new(llm, model.into())
    }

    /// Run the agent with the given user input.
    ///
    /// Executes the ReAct loop: sends the input to the LLM, collects any
    /// tool calls, executes them, and repeats until the model produces a
    /// final text response (no more tool calls).
    ///
    /// This is the simplest entry point.  Use [`run_with_events`](Self::run_with_events)
    /// if you need real-time streaming events (e.g. for a TUI).
    ///
    /// Returns the final assistant text on success.
    pub async fn run(&self, user_input: &str) -> Result<String, AgentError> {
        if self.ctx.streaming {
            self.run_streaming_loop(user_input, None).await
        } else {
            self.run_non_streaming_loop(user_input, None).await
        }
    }

    pub async fn run_with_events(
        &self,
        user_input: &str,
        tx: mpsc::UnboundedSender<AgentEvent>,
    ) -> Result<String, AgentError> {
        if self.ctx.streaming {
            self.run_streaming_loop(user_input, Some(tx)).await
        } else {
            self.run_non_streaming_loop(user_input, Some(tx)).await
        }
    }

    pub fn streaming(&self) -> bool {
        self.ctx.streaming
    }

    pub fn model(&self) -> &str {
        &self.ctx.model
    }

    pub fn max_steps(&self) -> usize {
        self.ctx.max_steps
    }

    pub fn memory(&self) -> &SharedMemory {
        &self.ctx.memory
    }
}

// ── Shared Loop Helpers ────────────────────────────────────────────────────────
//
// Extracted from run_streaming_loop and run_non_streaming_loop to eliminate
// ~500 lines of duplication. These methods are called by both loops.

impl<C: LLMClient> Agent<C> {
    /// Begin a run: notify hooks, emit RunStarted, push user message.
    fn begin_run(&self, user_input: &str, tx: &Option<mpsc::UnboundedSender<AgentEvent>>) {
        for hook in &self.ctx.hooks {
            hook.on_run_start("default", user_input, &self.ctx.memory);
        }
        if let Some(tx) = tx {
            let _ = tx.send(AgentEvent::RunStarted {
                session_id: "default".into(),
                user_input: user_input.to_string(),
            });
        }
        self.ctx
            .memory
            .write()
            .expect("memory lock poisoned")
            .push(Message::new(Role::User, user_input));
    }

    /// Run step-level hooks (on_step_start + on_llm_start) and return the
    /// context vector for the LLM call.
    fn prepare_llm_call(&self, steps: usize) -> Vec<Message> {
        for hook in &self.ctx.hooks {
            hook.on_step_start("default", steps, self.ctx.max_steps);
        }
        for hook in &self.ctx.hooks {
            hook.on_llm_start("default", &self.ctx.memory);
        }
        self.ctx
            .memory
            .read()
            .expect("memory lock poisoned")
            .to_context_vec()
    }

    /// Emit failure events, notify hooks, and return the error.
    fn fail_run(
        &self,
        err: AgentError,
        tx: &Option<mpsc::UnboundedSender<AgentEvent>>,
    ) -> Result<String, AgentError> {
        if let Some(tx) = tx {
            let _ = tx.send(AgentEvent::RunFailed {
                error: err.to_string(),
            });
        }
        for hook in &self.ctx.hooks {
            hook.on_run_finish(
                "default",
                &RunOutcome::Error {
                    error: err.to_string(),
                },
                &self.ctx.memory,
            );
        }
        if let Some(tx) = tx {
            let _ = tx.send(AgentEvent::Done);
        }
        Err(err)
    }

    /// Emit success events, notify hooks, and return the answer.
    fn finish_run(
        &self,
        answer: String,
        tx: &Option<mpsc::UnboundedSender<AgentEvent>>,
    ) -> Result<String, AgentError> {
        if let Some(tx) = tx {
            let _ = tx.send(AgentEvent::RunCompleted {
                answer: answer.clone(),
            });
        }
        for hook in &self.ctx.hooks {
            hook.on_run_finish(
                "default",
                &RunOutcome::Success {
                    answer: answer.clone(),
                },
                &self.ctx.memory,
            );
        }
        if let Some(tx) = tx {
            let _ = tx.send(AgentEvent::Done);
        }
        Ok(answer)
    }

    /// Execute all tool calls from an assistant message.
    ///
    /// Three-phase pipeline:
    /// 1. **Pre-flight** — run `before_tool_call` hooks sequentially (hooks can block
    ///    the calling thread for user intervention, so they must not run in parallel).
    ///    Blocked calls get rejection events + results pushed to memory immediately.
    /// 2. **Execution** — non-blocked tools run in parallel via `tokio::spawn`.
    ///    Each task drives its own [`ProgressStream`] and emits [`AgentEvent::ToolProgress`]
    ///    events in real time.  When there is only a single tool, the spawn overhead is
    ///    avoided and it runs inline.
    /// 3. **Post-flight** — after all tasks complete, results are merged with
    ///    blocked entries, sorted by original index, and `after_tool_call`/`on_tool_failed`
    ///    hooks are called in the parent.  Memory writes and terminal events
    ///    (`ToolSuccessful`/`ToolFailure`) are emitted in LLM tool-call order.
    async fn execute_tool_calls(
        &self,
        assistant_msg: &Message,
        tx: &Option<mpsc::UnboundedSender<AgentEvent>>,
    ) {
        // ── Emit ToolCall events before execution ──
        if let Some(tx) = tx
            && let Some(ref tool_calls) = assistant_msg.tool_calls
        {
            for tc in tool_calls {
                let _ = tx.send(AgentEvent::ToolCall {
                    id: tc.id.clone(),
                    name: tc.function.name.clone(),
                    arguments: tc.function.arguments.clone(),
                    origin: CallOrigin::Llm,
                });
            }
        }

        // ── Push assistant message to memory ──
        {
            let mut mem = self.ctx.memory.write().expect("memory lock poisoned");
            mem.push(assistant_msg.clone());
        }

        let tool_calls = match assistant_msg.tool_calls.as_ref() {
            Some(tcs) => tcs,
            None => return,
        };

        // ═══════════════════════════════════════════════════════════════
        // Phase 1 — Pre-flight: run before_tool_call hooks sequentially.
        // ═══════════════════════════════════════════════════════════════
        let mut ready: Vec<(usize, ToolCall)> = Vec::with_capacity(tool_calls.len());

        for (i, tc) in tool_calls.iter().enumerate() {
            let mut blocked = false;
            for hook in &self.ctx.hooks {
                if let Err(e) = hook.before_tool_call("default", tc) {
                    // Blocked — write rejection to memory + emit event immediately.
                    let rejection_msg = format!("Tool rejected: {e}");
                    self.ctx
                        .memory
                        .write()
                        .expect("memory lock poisoned")
                        .push(Message::tool_result(&tc.id, &rejection_msg));
                    if let Some(tx) = tx {
                        let _ = tx.send(AgentEvent::ToolRejected {
                            id: tc.id.clone(),
                            name: tc.function.name.clone(),
                            reason: e.to_string(),
                        });
                    }
                    blocked = true;
                    break;
                }
            }
            if !blocked {
                ready.push((i, tc.clone()));
            }
        }

        // ═══════════════════════════════════════════════════════════════
        // Phase 2 — Execute ready tools (inline for 1, parallel for N).
        // ═══════════════════════════════════════════════════════════════
        let outcomes: Vec<ToolOutcome> = if ready.len() == 1 {
            // Fast path: single tool — no spawn overhead.
            let (index, tc) = ready.into_iter().next().unwrap();
            let result = execute_one_tool(&self.ctx.tools, &tc, tx).await;
            vec![ToolOutcome { index, tc, result }]
        } else if ready.is_empty() {
            Vec::new()
        } else {
            // Parallel path: spawn one tokio task per tool.
            execute_parallel(&self.ctx.tools, ready, tx).await
        };

        // ═══════════════════════════════════════════════════════════════
        // Phase 3 — Post-flight: hooks, memory, terminal events (in order).
        // ═══════════════════════════════════════════════════════════════
        for outcome in &outcomes {
            match &outcome.result {
                ToolExecResult::Success { output } => {
                    for hook in &self.ctx.hooks {
                        hook.after_tool_call("default", &outcome.tc, output);
                    }
                    self.ctx
                        .memory
                        .write()
                        .expect("memory lock poisoned")
                        .push(Message::tool_result(&outcome.tc.id, output));
                    if let Some(tx) = tx {
                        let _ = tx.send(AgentEvent::ToolSuccessful {
                            id: outcome.tc.id.clone(),
                            name: outcome.tc.function.name.clone(),
                            output: output.clone(),
                        });
                    }
                }
                ToolExecResult::Failure { error } => {
                    for hook in &self.ctx.hooks {
                        hook.on_tool_failed("default", &outcome.tc, error);
                    }
                    self.ctx
                        .memory
                        .write()
                        .expect("memory lock poisoned")
                        .push(Message::tool_result(&outcome.tc.id, error));
                    if let Some(tx) = tx {
                        let _ = tx.send(AgentEvent::ToolFailure {
                            id: outcome.tc.id.clone(),
                            name: outcome.tc.function.name.clone(),
                            error: error.clone(),
                        });
                    }
                }
                ToolExecResult::NotFound { name } => {
                    let err_msg = format!("Tool not found: {name}");
                    for hook in &self.ctx.hooks {
                        hook.on_tool_failed("default", &outcome.tc, &err_msg);
                    }
                    self.ctx
                        .memory
                        .write()
                        .expect("memory lock poisoned")
                        .push(Message::tool_result(&outcome.tc.id, &err_msg));
                    if let Some(tx) = tx {
                        let _ = tx.send(AgentEvent::ToolFailure {
                            id: outcome.tc.id.clone(),
                            name: outcome.tc.function.name.clone(),
                            error: err_msg,
                        });
                    }
                }
            }
        }
    }
}

// ── Streaming Loop ────────────────────────────────────────────────────────────

impl<C: LLMClient> Agent<C> {
    /// Execute the **ReAct** (Reasoning + Acting) loop with SSE streaming.
    ///
    /// This is the core of the agent framework.  It implements a two-level
    /// loop that drives the LLM conversation until a terminal state is reached.
    ///
    /// # High-level flow
    ///
    /// ```text
    /// begin_run()                         // notify hooks, push user msg to memory
    ///   │
    ///   ▼
    /// ┌─────────────────────────────────┐
    /// │  Outer loop (step 1..max_steps)  │  ←─ ReAct loop
    /// │  ┌─────────────────────────────┐ │
    /// │  │ 1. prepare_llm_call()       │ │  ←─ run hooks, build context from memory
    /// │  │ 2. stream_with_retry()      │ │  ←─ open SSE connection to provider
    /// │  │                             │ │
    /// │  │  Inner loop (chunk by chunk)│ │  ←─ read SSE stream with 120s timeout
    /// │  │  ├─ emit_chunk_events()     │ │  ←─ forward Token/ReasoningToken to TUI
    /// │  │  └─ acc.ingest()            │ │  ←─ accumulate into final message
    /// │  │                             │ │
    /// │  │ 3. into_assistant_message() │ │  ←─ materialize the full response
    /// │  │ 4. on_llm_end() hooks       │ │
    /// │  └──────────┬──────────────────┘ │
    /// │             │                     │
    /// │     ┌───────┼───────┐             │
    /// │     ▼       ▼       ▼             │
    /// │  tool     length  final           │
    /// │  calls    (trunc) answer          │
    /// └─────┬───────┬───────┬─────────────┘
    ///       │       │       │
    ///       ▼       ▼       ▼
    ///   execute    push    finish_run()
    ///   tools      to      (success)
    ///   ──► loop   memory
    ///              ──► loop
    /// ```
    ///
    /// # The ReAct loop (outer loop)
    ///
    /// Each iteration of the outer loop is one "step."  The agent sends the
    /// full conversation context to the LLM, collects the response, and
    /// either (a) executes tool calls, (b) handles a truncated response, or
    /// (c) returns the final answer.
    ///
    /// The counter starts at 1 and is compared against [`EngineContext::max_steps`]
    /// (default 50).  If the counter is exceeded **before** the next LLM call,
    /// the run fails with [`AgentError::MaxStepsReached`].  Tools that produce
    /// their own content (e.g. a subagent that runs its own multi-step loop)
    /// do **not** count against this limit — only LLM calls count.
    ///
    /// # The chunk loop (inner loop)
    ///
    /// The SSE stream is read one chunk at a time.  Each chunk goes through
    /// two paths in parallel:
    ///
    /// | Component | Role |
    /// |-----------|------|
    /// | [`emit_chunk_events`] | Push `Token` / `ReasoningToken` events to the |
    /// |                       | TUI so the user sees text as it arrives.      |
    /// | [`StreamAccumulator`] | Buffer content, reasoning, and tool-call |
    /// |                       | fragments into a complete [`Message`].  |
    ///
    /// Both paths are driven from the same chunk — the accumulator always
    /// ingests; the TUI event sender is optional (no-op when `tx` is `None`,
    /// e.g. library mode).
    ///
    /// A per-chunk timeout of **120 seconds** guards against stalled SSE
    /// connections.  If no chunk arrives within that window, the run fails
    /// with [`AgentError::StreamTimeout`].
    ///
    /// # Terminal branches (after the inner loop completes)
    ///
    /// The assistant message is inspected to decide what happens next:
    ///
    /// | Condition | Action | Rationale |
    /// |-----------|--------|-----------|
    /// | **Has tool calls** | [`execute_tool_calls`] → **loop** | The LLM wants to |
    /// |                    |                                | use a tool; execute |
    /// |                    |                                | it, push results to |
    /// |                    |                                | memory, and let the |
    /// |                    |                                | LLM see the output |
    /// |                    |                                | next iteration. |
    /// | **Truncated**      | Push to memory → **loop** |   | `finish_reason` is |
    /// | (`FinishReason::Length`) |                         | `"length"` — the model |
    /// |                    |                                | hit its max-token |
    /// |                    |                                | limit mid-response. |
    /// |                    |                                | The partial message |
    /// |                    |                                | stays in context so |
    /// |                    |                                | the model can continue. |
    /// | **Neither**        | [`finish_run`] → **return** |   | The model produced a |
    /// |                    |                                | final text answer. |
    /// |                    |                                | Push to memory, emit |
    /// |                    |                                | `RunCompleted`, then |
    /// |                    |                                | `Done`, and return. |
    ///
    /// # Truncation handling
    ///
    /// When the provider returns `FinishReason::Length`, the model's output
    /// was cut off before it finished.  This typically happens when the model
    /// is generating a long code block or document.  Instead of returning a
    /// partial answer, the loop pushes the truncated message to memory and
    /// spins again — the model will see its own partial output in context and
    /// continue from where it left off.  The next LLM call naturally
    /// resumes the thought because the assistant message without tool calls
    /// but with `finish_reason: "length"` is in the history.
    ///
    /// # Cancellation
    ///
    /// This method does **not** directly handle cancellation — the caller
    /// (typically a TUI) should wrap the future in a [`tokio::select!`] with
    /// a cancellation channel, then call [`fail_run`] or send `AgentEvent::Cancelled`
    /// externally.  See the `loomis` binary for the TUI-side cancellation pattern.
    async fn run_streaming_loop(
        &self,
        user_input: &str,
        tx: Option<mpsc::UnboundedSender<AgentEvent>>,
    ) -> Result<String, AgentError> {
        self.begin_run(user_input, &tx);

        let mut steps = 0;
        loop {
            if steps >= self.ctx.max_steps {
                return self.fail_run(AgentError::MaxStepsReached(self.ctx.max_steps), &tx);
            }
            steps += 1;

            // ── Drain any user hints queued during tool execution. ──
            // Must happen here — after the previous step's tool results
            // are committed to memory, but before building the context
            // vector for the next LLM call.  Inserting a user message
            // between an assistant tool_calls message and its tool
            // results violates the provider API contract.
            {
                let mut pending = self
                    .ctx
                    .pending_hints
                    .lock()
                    .expect("pending hints lock poisoned");
                if !pending.is_empty() {
                    let mut mem = self.ctx.memory.write().expect("memory lock poisoned");
                    for msg in pending.drain(..) {
                        mem.push(msg);
                    }
                }
            }

            // ── Build context: run on_step_start + on_llm_start hooks, then
            //    snapshot the full conversation history from memory.  The
            //    context includes the system prompt, all prior user/assistant
            //    messages, and any tool-call results from previous steps.
            let messages = self.prepare_llm_call(steps);
            let tools = self.ctx.tools.to_tool_defs();
            let request = CompletionRequest::new(&self.ctx.model, messages)
                .with_stream(true)
                .with_tools(tools);

            // ── Open SSE stream with retry + exponential backoff ──
            let mut stream = match stream_with_retry(
                &self.ctx.llm,
                request.clone(),
                self.ctx.max_retries,
                &self.ctx.hooks,
            )
            .await
            {
                Ok(s) => s,
                Err(e) => return self.fail_run(e, &tx),
            };

            // ── Per-chunk timeout — prevents hanging forever on a stalled
            //    SSE connection.  120s is long enough for the provider to
            //    generate a very large token, but short enough that the user
            //    isn't waiting indefinitely.
            const STREAM_CHUNK_TIMEOUT_SECS: u64 = 120;

            // ── Inner loop: drain the SSE stream chunk by chunk ──
            let mut acc = StreamAccumulator::new();
            loop {
                let chunk_result = match tokio::time::timeout(
                    Duration::from_secs(STREAM_CHUNK_TIMEOUT_SECS),
                    stream.next(),
                )
                .await
                {
                    Ok(Some(result)) => result,
                    Ok(None) => break, // stream exhausted normally
                    Err(_elapsed) => {
                        return self.fail_run(AgentError::StreamTimeout, &tx);
                    }
                };
                let chunk = match chunk_result {
                    Ok(c) => c,
                    Err(e) => return self.fail_run(AgentError::Provider(e), &tx),
                };
                if let Some(ref tx) = tx {
                    emit_chunk_events(tx, &chunk, &mut acc);
                } else {
                    acc.ingest(&chunk);
                }
            }

            // ── Materialize the full assistant message from accumulated
            //    deltas, then notify hooks.
            let (assistant_msg, finish_reason) = acc.into_assistant_message();
            for hook in &self.ctx.hooks {
                hook.on_llm_end("default", &assistant_msg);
            }

            // ── Decide next action ──
            let has_tool_calls = assistant_msg
                .tool_calls
                .as_ref()
                .is_some_and(|tcs| !tcs.is_empty());
            let is_truncated = matches!(finish_reason, Some(FinishReason::Length));

            if has_tool_calls {
                // Tool calls → execute them, push results to memory, loop
                // again so the LLM can see the tool outputs.
                self.execute_tool_calls(&assistant_msg, &tx).await;
            } else if is_truncated {
                // Truncated → push the partial message to memory and spin
                // again.  The next LLM call will see its own partial output
                // in context and continue generation.
                self.ctx
                    .memory
                    .write()
                    .expect("memory lock poisoned")
                    .push(assistant_msg);
            } else {
                // Final answer → push to memory and return.
                self.ctx
                    .memory
                    .write()
                    .expect("memory lock poisoned")
                    .push(assistant_msg.clone());
                return self.finish_run(assistant_msg.content, &tx);
            }
        }
    }

    async fn run_non_streaming_loop(
        &self,
        user_input: &str,
        tx: Option<mpsc::UnboundedSender<AgentEvent>>,
    ) -> Result<String, AgentError> {
        self.begin_run(user_input, &tx);

        let mut steps = 0;
        loop {
            if steps >= self.ctx.max_steps {
                return self.fail_run(AgentError::MaxStepsReached(self.ctx.max_steps), &tx);
            }
            steps += 1;

            // ── Drain any user hints queued during tool execution. ──
            {
                let mut pending = self
                    .ctx
                    .pending_hints
                    .lock()
                    .expect("pending hints lock poisoned");
                if !pending.is_empty() {
                    let mut mem = self.ctx.memory.write().expect("memory lock poisoned");
                    for msg in pending.drain(..) {
                        mem.push(msg);
                    }
                }
            }

            let messages = self.prepare_llm_call(steps);
            let tools = self.ctx.tools.to_tool_defs();
            let request = CompletionRequest::new(&self.ctx.model, messages)
                .with_stream(false)
                .with_tools(tools);

            let response = match generate_with_retry(
                &self.ctx.llm,
                request,
                self.ctx.max_retries,
                &self.ctx.hooks,
            )
            .await
            {
                Ok(r) => r,
                Err(e) => return self.fail_run(e, &tx),
            };

            let choice = match response.choices.into_iter().next() {
                Some(c) => c,
                None => return self.fail_run(AgentError::NoChoices, &tx),
            };

            let content = choice.message.content.unwrap_or_default();
            let tool_calls = choice.message.tool_calls;
            let has_tool_calls = tool_calls.as_ref().is_some_and(|tcs| !tcs.is_empty());
            let is_truncated = matches!(&choice.finish_reason, Some(FinishReason::Length));
            let reasoning = choice.message.reasoning_content;

            let msg = Message {
                role: Role::Assistant,
                content: content.clone(),
                tool_calls: tool_calls.clone(),
                tool_call_id: None,
                name: None,
            };

            for hook in &self.ctx.hooks {
                hook.on_llm_end("default", &msg);
            }

            // Emit tokens for TUI display (non-streaming: single bulk event).
            if let Some(ref tx) = tx {
                if let Some(ref r) = reasoning
                    && !r.is_empty()
                {
                    let _ = tx.send(AgentEvent::ReasoningToken(r.clone()));
                }
                let _ = tx.send(AgentEvent::Token(content.clone()));
            }

            if has_tool_calls {
                // Tool calls: delegate to shared executor.
                self.execute_tool_calls(&msg, &tx).await;
            } else if is_truncated {
                self.ctx
                    .memory
                    .write()
                    .expect("memory lock poisoned")
                    .push(msg);
            } else {
                self.ctx
                    .memory
                    .write()
                    .expect("memory lock poisoned")
                    .push(msg);
                return self.finish_run(content, &tx);
            }
        }
    }
}

// ── StreamAccumulator ─────────────────────────────────────────────────────────
//
// The SSE protocol delivers LLM responses as a sequence of small, incremental
// "deltas" (chunks).  A single assistant message can span dozens of chunks:
// content tokens arrive one at a time, tool-call fragments are spread across
// multiple chunks, and reasoning (chain-of-thought) is interleaved with
// everything else.  `StreamAccumulator` is the buffer that stitches these
// deltas back into a complete [`Message`].

/// Accumulates incremental SSE deltas into a complete assistant [`Message`].
///
/// # Why this exists
///
/// The DeepSeek (and OpenAI-compatible) streaming API sends responses as
/// Server-Sent Events.  Each chunk carries a [`StreamChunk`] with a `delta`
/// field that contains **partial** updates:
///
/// | Delta field | Arrival pattern |
/// |-------------|-----------------|
/// | `content` | One or a few text tokens per chunk, concatenated in order |
/// | `reasoning_content` | Same as content, but for chain-of-thought |
/// | `tool_calls` | Fragmented — `id` and `name` may arrive in one chunk, |
/// |             | `arguments` dribble in over many subsequent chunks |
/// | `finish_reason` | `null` on every chunk except the final one |
///
/// # Tool-call fragmentation
///
/// This is the tricky part.  The provider sends tool calls incrementally:
///
/// ```text
/// Chunk 1:  delta.tool_calls[0] = { index: 0, id: "call_1", function.name: "read" }
/// Chunk 2:  delta.tool_calls[0] = { index: 0, function.arguments: "{\"file" }
/// Chunk 3:  delta.tool_calls[0] = { index: 0, function.arguments: "_path\": " }
/// Chunk 4:  delta.tool_calls[0] = { index: 0, function.arguments: "\"src/main.rs\"}" }
/// Chunk 5:  (final — finish_reason: "tool_calls")
/// ```
///
/// We key by `tc.index` (a `u32`), creating a [`ToolCallAccumulator`] on first
/// sight and appending argument fragments on subsequent chunks.  The `id` and
/// `name` are set once (first non-empty value wins — they're typically only
/// populated in the first chunk for a given index).
///
/// # `BTreeMap` ordering
///
/// A [`BTreeMap<u32, _>`] is used instead of [`HashMap`] so that when we
/// materialize the tool calls in [`into_assistant_message`], they are emitted
/// in the same order the LLM declared them.  Tool execution order matters:
/// the LLM may intend `tool[0]` to run before `tool[1]`.
struct StreamAccumulator {
    /// Accumulated text content (the assistant's "answer" text).
    content: String,
    /// Accumulated reasoning / chain-of-thought text.
    reasoning: String,
    /// In-progress tool calls, keyed by the LLM-assigned index.
    tool_calls: BTreeMap<u32, ToolCallAccumulator>,
    /// The `finish_reason` from the terminal chunk; `None` until the
    /// final chunk arrives.
    finish_reason: Option<FinishReason>,
}

/// Buffers incremental fields for a single tool call during streaming.
///
/// The SSE protocol fragments tool calls across multiple chunks —
/// `id` and `name` typically arrive in one chunk, while `arguments`
/// stream in as incremental JSON fragments over subsequent chunks.
struct ToolCallAccumulator {
    id: String,
    name: String,
    arguments: String,
}

impl StreamAccumulator {
    fn new() -> Self {
        Self {
            content: String::new(),
            reasoning: String::new(),
            tool_calls: BTreeMap::new(),
            finish_reason: None,
        }
    }

    /// Ingest one SSE chunk, appending its deltas to the internal buffers.
    ///
    /// Called once per chunk in the inner streaming loop.  For each
    /// [`choice`](StreamChunk::choices) in the chunk:
    ///
    /// - **Text content** and **reasoning** are appended verbatim to their
    ///   respective `String` buffers.  These are simple concatenations —
    ///   the provider sends them in display order.
    ///
    /// - **Tool calls** are merged by `index`.  A [`ToolCallAccumulator`] is
    ///   created on first encounter; subsequent chunks append `function.arguments`
    ///   fragments and overwrite `id`/`function.name` if the incoming chunk
    ///   carries non-empty values for those fields.
    ///
    /// - **`finish_reason`** is captured from the final chunk (it's `null` on
    ///   all intermediate chunks).  Only the last non-null value is retained.
    ///
    /// This method is deliberately infallible — SSE parse errors are handled
    /// upstream in [`stream_with_retry`], and this is pure string accumulation.
    fn ingest(&mut self, chunk: &StreamChunk) {
        for choice in &chunk.choices {
            if let Some(ref c) = choice.delta.content {
                self.content.push_str(c);
            }
            if let Some(ref r) = choice.delta.reasoning_content {
                self.reasoning.push_str(r);
            }
            if let Some(ref tool_calls) = choice.delta.tool_calls {
                for tc in tool_calls {
                    let entry =
                        self.tool_calls
                            .entry(tc.index)
                            .or_insert_with(|| ToolCallAccumulator {
                                id: tc.id.clone(),
                                name: String::new(),
                                arguments: String::new(),
                            });
                    // id and name are typically set in the first chunk for a
                    // given index; subsequent chunks carry only argument fragments.
                    // Non-empty checks prevent clobbering with empty strings.
                    if !tc.id.is_empty() {
                        entry.id = tc.id.clone();
                    }
                    if !tc.function.name.is_empty() {
                        entry.name = tc.function.name.clone();
                    }
                    // Arguments are always appended — they arrive as JSON
                    // fragments spread across multiple chunks.
                    entry.arguments.push_str(&tc.function.arguments);
                }
            }
            // finish_reason is `null` on every intermediate chunk.  Only the
            // terminal chunk carries a value like `"stop"`, `"tool_calls"`,
            // or `"length"`.
            if let Some(ref fr) = choice.finish_reason {
                self.finish_reason = Some(fr.clone());
            }
        }
    }

    /// Materialize all accumulated deltas into a single assistant [`Message`].
    ///
    /// Consumes `self`.  Returns the complete message plus the `finish_reason`
    /// from the terminal chunk (if any).
    ///
    /// # Tool-call materialization
    ///
    /// The `BTreeMap<u32, ToolCallAccumulator>` is drained in index order,
    /// producing a `Vec<ToolCall>` where each entry has:
    /// - `index: 0` (set after draining — the field is not meaningful on
    ///   constructed messages, only for the provider protocol)
    /// - `id`, `function.name`, `function.arguments` — the fully accumulated values
    ///
    /// An empty tool-calls list is normalized to `None` (the provider
    /// distinguishes "no tool calls" from "empty tool-calls list").
    fn into_assistant_message(self) -> (Message, Option<FinishReason>) {
        let tool_calls: Vec<ToolCall> = self
            .tool_calls
            .into_values()
            .map(|acc| ToolCall {
                index: 0,
                id: acc.id,
                kind: ToolCallKind::Function,
                function: ToolCallFunction {
                    name: acc.name,
                    arguments: acc.arguments,
                },
            })
            .collect();

        let tool_calls = if tool_calls.is_empty() {
            None
        } else {
            Some(tool_calls)
        };

        let msg = Message {
            role: Role::Assistant,
            content: self.content,
            tool_calls,
            tool_call_id: None,
            name: None,
        };
        (msg, self.finish_reason)
    }
}

// ── Event emission ────────────────────────────────────────────────────────────

/// Push per-chunk events to the TUI channel and update the accumulator.
///
/// This is the glue between the streaming pipeline and the user interface.
/// For each choice in the chunk:
///
/// - **`content` delta** → emits [`AgentEvent::Token`] so the TUI can render
///   text character-by-character as the model generates it.
/// - **`reasoning_content` delta** → emits [`AgentEvent::ReasoningToken`] for
///   chain-of-thought display (typically rendered in a collapsible section or
///   dimmed style in the TUI).
///
/// After emitting events, the chunk is passed to [`StreamAccumulator::ingest`]
/// so the full message can be materialized later.
///
/// # Why two paths?
///
/// The TUI needs **immediate** text for real-time rendering, but the agent
/// loop needs the **complete** message for tool-call extraction and memory
/// storage.  Events are fire-and-forget (the `let _ =` drops send errors
/// when the TUI has gone away), while accumulation is infallible.
///
/// When `tx` is `None` (library mode — no TUI attached), this function is
/// not called at all; the inner loop calls `acc.ingest()` directly to skip
/// the event-send overhead.
fn emit_chunk_events(
    tx: &mpsc::UnboundedSender<AgentEvent>,
    chunk: &StreamChunk,
    acc: &mut StreamAccumulator,
) {
    for choice in &chunk.choices {
        if let Some(ref c) = choice.delta.content {
            let _ = tx.send(AgentEvent::Token(c.clone()));
        }
        if let Some(ref r) = choice.delta.reasoning_content {
            let _ = tx.send(AgentEvent::ReasoningToken(r.clone()));
        }
    }
    acc.ingest(chunk);
}

// ── Parallel tool execution helpers ──────────────────────────────────────────

/// Outcome of a single tool execution, produced by a spawned task or inline
/// execution in Phase 2.
struct ToolOutcome {
    /// Original position in the LLM's tool-call list (used for ordering).
    index: usize,
    /// The tool call that was executed.
    tc: ToolCall,
    /// Execution result.
    result: ToolExecResult,
}

/// Final result of driving a tool's [`ProgressStream`] to completion.
enum ToolExecResult {
    /// Tool completed successfully — carries the final output from
    /// [`Progress::Done`].
    Success { output: String },
    /// The tool returned an error from [`ToolRegistry::execute_stream`].
    Failure { error: String },
    /// The tool name was not found in the registry.
    NotFound { name: String },
}

/// Drive a single tool's [`ProgressStream`] to completion, emitting
/// [`AgentEvent::ToolProgress`] events in real-time.
///
/// Called from spawned tasks (parallel path) or inline (fast path).
async fn execute_one_tool(
    tools: &ToolRegistry,
    tc: &ToolCall,
    tx: &Option<mpsc::UnboundedSender<AgentEvent>>,
) -> ToolExecResult {
    let tool_result = tools.execute_stream(&tc.function.name, &tc.function.arguments);

    match tool_result {
        Some(Ok(mut stream)) => {
            let mut final_output = String::new();
            while let Some(progress) = stream.next().await {
                match progress {
                    Progress::InProgress(msg) => {
                        if let Some(tx) = tx {
                            let _ = tx.send(AgentEvent::ToolProgress {
                                id: tc.id.clone(),
                                name: tc.function.name.clone(),
                                message: msg,
                            });
                        }
                    }
                    Progress::Done(output) => final_output = output,
                }
            }
            ToolExecResult::Success {
                output: final_output,
            }
        }
        Some(Err(e)) => ToolExecResult::Failure {
            error: e.to_string(),
        },
        None => ToolExecResult::NotFound {
            name: tc.function.name.clone(),
        },
    }
}

/// Spawn one tokio task per tool and collect results.
///
/// Each task owns a cloned [`ToolCall`], an `Arc<ToolRegistry>`, and a
/// clone of the event sender.  Results are collected and sorted by the
/// original index so the parent can process them in LLM tool-call order.
async fn execute_parallel(
    tools: &Arc<ToolRegistry>,
    ready: Vec<(usize, ToolCall)>,
    tx: &Option<mpsc::UnboundedSender<AgentEvent>>,
) -> Vec<ToolOutcome> {
    let tools = Arc::clone(tools);
    let mut handles: Vec<tokio::task::JoinHandle<ToolOutcome>> = Vec::with_capacity(ready.len());

    for (index, tc) in ready {
        let tools = Arc::clone(&tools);
        let tx = tx.clone();
        handles.push(tokio::spawn(async move {
            let result = execute_one_tool(&tools, &tc, &tx).await;
            ToolOutcome { index, tc, result }
        }));
    }

    // Collect results, tolerating panics in spawned tasks.
    let mut outcomes = Vec::with_capacity(handles.len());
    for handle in handles {
        match handle.await {
            Ok(outcome) => outcomes.push(outcome),
            Err(join_err) => {
                // A spawned task panicked — fabricate a synthetic failure.
                // The ToolOutcome struct needs a tc; use a minimal one with
                // the panic message.  Since we can't recover the original
                // ToolCall from a JoinError, log the panic and skip.
                // (tokio::spawn panics are extremely rare in tool execution.)
                let panic_msg = if let Ok(reason) = join_err.try_into_panic() {
                    let reason = reason
                        .downcast_ref::<&str>()
                        .map(|s| s.to_string())
                        .or_else(|| reason.downcast_ref::<String>().cloned())
                        .unwrap_or_else(|| "unknown panic".into());
                    format!("Tool task panicked: {reason}")
                } else {
                    "Tool task was cancelled".into()
                };
                // We lost the original index and tc — this is an edge case.
                // Push a synthetic outcome with an impossible index so it
                // appears at the end of the sorted list.
                outcomes.push(ToolOutcome {
                    index: usize::MAX,
                    tc: ToolCall {
                        index: 0,
                        id: String::new(),
                        kind: ToolCallKind::Function,
                        function: ToolCallFunction {
                            name: "unknown".into(),
                            arguments: String::new(),
                        },
                    },
                    result: ToolExecResult::Failure { error: panic_msg },
                });
            }
        }
    }

    // Restore LLM's original tool-call order.
    outcomes.sort_by_key(|o| o.index);
    outcomes
}

// ── Retry helpers ─────────────────────────────────────────────────────────────

/// Base delay in milliseconds for exponential backoff on retryable failures.
const RETRY_BASE_MS: u64 = 500;
/// Exponential factor applied to the retry count.
const RETRY_EXP_FACTOR: u32 = 2;

async fn generate_with_retry(
    client: &impl LLMClient,
    request: CompletionRequest,
    max_retries: usize,
    hooks: &[Box<dyn AgentHook>],
) -> Result<CompletionResponse, AgentError> {
    let mut last_err = None;
    for attempt in 0..=max_retries {
        if attempt > 0 {
            let backoff = Duration::from_millis(
                RETRY_BASE_MS * (RETRY_EXP_FACTOR as u64).pow(attempt as u32 - 1),
            );
            tokio::time::sleep(backoff).await;
        }
        match client.generate(request.clone()).await {
            Ok(resp) => return Ok(resp),
            Err(e) => {
                let will_retry = is_retryable(&e) && attempt < max_retries;
                for hook in hooks {
                    hook.on_llm_error("default", &e, attempt, will_retry);
                }
                if !is_retryable(&e) {
                    return Err(AgentError::Provider(e));
                }
                last_err = Some(e);
            }
        }
    }
    Err(AgentError::Provider(last_err.unwrap()))
}

async fn stream_with_retry(
    client: &impl LLMClient,
    request: CompletionRequest,
    max_retries: usize,
    hooks: &[Box<dyn AgentHook>],
) -> Result<futures_util::stream::BoxStream<'static, Result<StreamChunk, ProviderError>>, AgentError>
{
    let mut last_err = None;
    for attempt in 0..=max_retries {
        if attempt > 0 {
            let backoff = Duration::from_millis(
                RETRY_BASE_MS * (RETRY_EXP_FACTOR as u64).pow(attempt as u32 - 1),
            );
            tokio::time::sleep(backoff).await;
        }
        match client.stream(request.clone()).await {
            Ok(stream) => return Ok(stream),
            Err(e) => {
                let will_retry = is_retryable(&e) && attempt < max_retries;
                for hook in hooks {
                    hook.on_llm_error("default", &e, attempt, will_retry);
                }
                if !is_retryable(&e) {
                    return Err(AgentError::Provider(e));
                }
                last_err = Some(e);
            }
        }
    }
    Err(AgentError::Provider(last_err.unwrap()))
}

fn is_retryable(err: &ProviderError) -> bool {
    match err {
        ProviderError::Http { .. } => true,
        ProviderError::Api { status, .. } => status >= &500u16,
        ProviderError::Parse { .. } => false,
        ProviderError::StreamingNotSupported => false,
        _ => false,
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_stream_accumulator_text_only() {
        let mut acc = StreamAccumulator::new();
        let chunk: StreamChunk = serde_json::from_str(
            r#"{"id":"1","object":"c","created":1,"model":"m","choices":[{"index":0,"delta":{"content":"Hello"},"finish_reason":null}],"usage":null}"#,
        )
        .unwrap();
        acc.ingest(&chunk);
        let (msg, finish_reason) = acc.into_assistant_message();
        assert_eq!(msg.content, "Hello");
        assert!(msg.tool_calls.is_none());
        assert!(finish_reason.is_none());
    }

    #[test]
    fn test_agent_error_display() {
        assert!(AgentError::MaxStepsReached(10).to_string().contains("10"));
        assert!(AgentError::NoOutput.to_string().contains("empty"));
    }

    #[test]
    fn test_is_retryable() {
        assert!(is_retryable(&ProviderError::Http {
            message: "timeout".into()
        }));
        assert!(is_retryable(&ProviderError::Api {
            status: 503,
            body: "".into()
        }));
        assert!(!is_retryable(&ProviderError::Api {
            status: 400,
            body: "".into()
        }));
        assert!(!is_retryable(&ProviderError::Parse {
            message: "oops".into()
        }));
    }
}
