//! # Agent — Core ReAct Loop
//!
//! Drives autonomous tool-using conversations with an LLM provider.

use std::collections::BTreeMap;
use std::fmt;
use std::time::Duration;

use futures_util::StreamExt;
use tokio::sync::mpsc;

use memory::SharedMemory;
use provider::{
    CompletionRequest, CompletionResponse, LLMClient, Message, ProviderError, Role, StreamChunk,
    ToolCall, ToolCallFunction, ToolCallType,
};
use tools::{Progress, ToolError};

use crate::builder::AgentBuilder;
use crate::context::EngineContext;
use crate::hooks::AgentHook;

// ── AgentError ────────────────────────────────────────────────────────────────

#[derive(Debug)]
pub enum AgentError {
    Provider(ProviderError),
    Tool { name: String, error: ToolError },
    MaxStepsReached(usize),
    NoOutput,
    NoChoices,
    Memory(String),
    ToolRejected { name: String, reason: String },
}

impl fmt::Display for AgentError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Provider(e) => write!(f, "provider error: {e}"),
            Self::Tool { name, error } => write!(f, "tool '{name}' error: {error}"),
            Self::MaxStepsReached(n) => write!(f, "max steps ({n}) reached"),
            Self::NoOutput => write!(f, "model returned empty output"),
            Self::NoChoices => write!(f, "response has no choices"),
            Self::Memory(msg) => write!(f, "memory error: {msg}"),
            Self::ToolRejected { name, reason } => write!(f, "tool '{name}' rejected: {reason}"),
        }
    }
}

impl std::error::Error for AgentError {}

impl From<ProviderError> for AgentError {
    fn from(e: ProviderError) -> Self {
        Self::Provider(e)
    }
}

// ── CallOrigin ────────────────────────────────────────────────────────────────

/// Distinguishes who initiated a tool or command invocation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CallOrigin {
    /// The LLM decided to invoke a tool.
    Llm,
    /// The user initiated this directly (e.g. `!git status` in a TUI).
    User,
}

// ── Intervene ─────────────────────────────────────────────────────────────────

/// A hook or sandbox component is asking the user to make a decision.
///
/// The application renders this as an interactive prompt.  The user picks
/// one of the [`options`](Self::options).  If the chosen option's label
/// ends with `…` (U+2026), the application opens a text-input dialog and
/// the free-form text is returned in [`InterveneResponse::custom_text`].
#[derive(Debug, Clone)]
pub struct InterveneRequest {
    /// Opaque id generated by the requester — echoed back in the response
    /// so the requester can correlate when multiple requests are in flight.
    pub request_id: String,
    /// Short question displayed prominently.
    /// e.g. `"Approve shell command?"`, `"Choose build system"`
    pub title: String,
    /// Detailed context — the shell command, a diff, conflicting paths, etc.
    pub description: String,
    /// One or more choices.  For simple confirmations use
    /// `["Approve", "Deny"]`.  An option whose label ends with `…`
    /// triggers free-form text input.
    pub options: Vec<String>,
}

/// The user's answer to an [`InterveneRequest`].
#[derive(Debug, Clone)]
pub struct InterveneResponse {
    /// Index into [`InterveneRequest::options`] that the user selected,
    /// or `None` if the user dismissed the prompt (Esc / cancel).
    pub chosen: Option<usize>,
    /// Free-form text when the user selected a `…`-suffixed option
    /// and typed a custom answer.
    pub custom_text: Option<String>,
}

// ── RunOutcome ────────────────────────────────────────────────────────────────

/// Describes how an agent run terminated.
///
/// Passed to [`AgentHook::on_run_finish`](crate::AgentHook::on_run_finish) so
/// hooks can distinguish success, error, and cancellation.
#[derive(Debug, Clone)]
pub enum RunOutcome {
    /// Agent completed successfully with the final answer text.
    Success {
        /// The final assistant text returned to the caller.
        answer: String,
    },
    /// Agent terminated with an error (provider, tool, max-steps, etc.).
    Error {
        /// Human-readable error message from [`AgentError::to_string`].
        error: String,
    },
    /// The user cancelled the run (e.g. Ctrl+C in the TUI).
    Cancelled,
}

// ── AgentEvent ────────────────────────────────────────────────────────────────

/// Streaming events produced during an agent run.
///
/// Events flow from the agent loop to the application (e.g. a TUI) over a
/// single [`tokio::sync::mpsc::unbounded_channel`].  Every event type the
/// framework can produce is a variant of this enum — applications never
/// need to define their own custom event type.
#[derive(Debug, Clone)]
pub enum AgentEvent {
    /// An agent run has started — the TUI should enter "streaming" mode.
    RunStarted {
        /// Opaque session identifier (currently `"default"`).
        session_id: String,
        /// The user input that triggered this run.
        user_input: String,
    },
    /// A text token from the LLM response stream.
    Token(String),
    /// A reasoning / chain-of-thought token.
    ReasoningToken(String),
    /// A tool or user-command invocation, emitted before execution begins.
    /// Use [`origin`](CallOrigin) to distinguish LLM tool calls from
    /// user-initiated commands (e.g. `!git status`).
    ToolCall {
        id: String,
        name: String,
        arguments: String,
        /// Who initiated this call — the LLM or the user.
        origin: CallOrigin,
    },
    /// Result from a completed tool or user-command execution (success).
    ToolResult {
        id: String,
        name: String,
        output: String,
    },
    /// Tool execution failed — emitted instead of [`ToolResult`](AgentEvent::ToolResult)
    /// when the tool returns an error or is not found.
    ToolFailure {
        id: String,
        name: String,
        error: String,
    },
    /// Real-time progress update from a running tool.
    ToolProgress {
        id: String,
        name: String,
        message: String,
    },
    /// A hook is requesting user intervention before proceeding.
    /// The application should render the request, collect an answer, and
    /// send back an [`InterveneResponse`] via the intervention channel.
    NeedUserIntervene(InterveneRequest),
    /// The agent completed the run successfully — carries the final answer.
    /// Emitted before [`Done`](AgentEvent::Done).
    RunCompleted {
        /// The final assistant text returned by the model.
        answer: String,
    },
    /// The agent run terminated with an error.
    /// Emitted before [`Done`](AgentEvent::Done).
    RunFailed {
        /// Human-readable error message.
        error: String,
    },
    /// The user cancelled the agent run (e.g. Ctrl+C).
    /// Emitted before [`Done`](AgentEvent::Done).
    Cancelled,
    /// The agent has finished the current run — reset streaming state.
    /// Always the final event, regardless of success, failure, or cancellation.
    Done,
}

// ── Agent ─────────────────────────────────────────────────────────────────────

pub struct Agent<C: LLMClient> {
    ctx: EngineContext<C>,
}

impl<C: LLMClient> Agent<C> {
    /// Create a new [`Agent`] from a fully-configured [`EngineContext`].
    ///
    /// This is the **advanced** entry point.  Most users should prefer
    /// [`Agent::builder`] which provides a fluent API with sensible defaults.
    pub fn new(ctx: EngineContext<C>) -> Self {
        Self { ctx }
    }

    /// Create an [`AgentBuilder`] with the two **required** dependencies.
    ///
    /// All other settings have sensible defaults:
    ///
    /// | Field | Default |
    /// |-------|---------|
    /// | `memory` | Auto-created empty [`Memory`] |
    /// | `tools` | Empty registry |
    /// | `hooks` | Empty |
    /// | `system_prompt` | `None` |
    /// | `max_steps` | `50` |
    /// | `max_retries` | `3` |
    /// | `streaming` | `true` |
    /// | Compaction | Off — opt in via `.with_micro_compact()` / `.with_macro_compact()` |
    ///
    /// # Example
    ///
    /// ```ignore
    /// let agent = Agent::builder(client, "deepseek-v4")
    ///     .system_prompt("You are a helpful assistant.")
    ///     .tool(calculator_tool)
    ///     .build();
    ///
    /// let answer = agent.run("2+2=?").await?;
    /// ```
    pub fn builder(llm: C, model: impl Into<String>) -> AgentBuilder<C> {
        AgentBuilder::new(llm, model.into())
    }

    /// Run the agent with the given user input.
    ///
    /// Executes the ReAct loop: sends the input to the LLM, collects any
    /// tool calls, executes them, and repeats until the model produces a
    /// final text response (no more tool calls).
    ///
    /// This is the simplest entry point.  Use [`run_with_events`](Self::run_with_events)
    /// if you need real-time streaming events (e.g. for a TUI).
    ///
    /// Returns the final assistant text on success.
    pub async fn run(&self, user_input: &str) -> Result<String, AgentError> {
        if self.ctx.streaming {
            self.run_streaming_loop(user_input, None).await
        } else {
            self.run_non_streaming_loop(user_input, None).await
        }
    }

    pub async fn run_with_events(
        &self,
        user_input: &str,
        tx: mpsc::UnboundedSender<AgentEvent>,
    ) -> Result<String, AgentError> {
        if self.ctx.streaming {
            self.run_streaming_loop(user_input, Some(tx)).await
        } else {
            self.run_non_streaming_loop(user_input, Some(tx)).await
        }
    }

    pub fn streaming(&self) -> bool {
        self.ctx.streaming
    }

    pub fn model(&self) -> &str {
        &self.ctx.model
    }

    pub fn max_steps(&self) -> usize {
        self.ctx.max_steps
    }

    pub fn memory(&self) -> &SharedMemory {
        &self.ctx.memory
    }
}

// ── Streaming Loop ────────────────────────────────────────────────────────────

impl<C: LLMClient> Agent<C> {
    async fn run_streaming_loop(
        &self,
        user_input: &str,
        tx: Option<mpsc::UnboundedSender<AgentEvent>>,
    ) -> Result<String, AgentError> {
        for hook in &self.ctx.hooks {
            hook.on_run_start("default", user_input);
        }

        // Notify the application that a run has started.
        if let Some(ref tx) = tx {
            let _ = tx.send(AgentEvent::RunStarted {
                session_id: "default".into(),
                user_input: user_input.to_string(),
            });
        }

        let mut steps = 0;
        loop {
            if steps >= self.ctx.max_steps {
                let err = AgentError::MaxStepsReached(self.ctx.max_steps);
                if let Some(ref tx) = tx {
                    let _ = tx.send(AgentEvent::RunFailed {
                        error: err.to_string(),
                    });
                }
                for hook in &self.ctx.hooks {
                    hook.on_run_finish(
                        "default",
                        &RunOutcome::Error {
                            error: err.to_string(),
                        },
                    );
                }
                if let Some(ref tx) = tx {
                    let _ = tx.send(AgentEvent::Done);
                }
                return Err(err);
            }
            steps += 1;

            // Step-level hooks — called before on_llm_start each iteration.
            for hook in &self.ctx.hooks {
                hook.on_step_start("default", steps, self.ctx.max_steps);
            }

            // Run pre-LLM hooks (compaction, etc.).
            for hook in &self.ctx.hooks {
                hook.on_llm_start("default", &self.ctx.memory);
            }

            let messages = {
                let mem = self.ctx.memory.read().unwrap();
                mem.to_context_vec()
            };

            let tools = self.ctx.tools.to_tool_defs();
            let request = CompletionRequest::new(&self.ctx.model, messages)
                .with_stream(true)
                .with_tools(tools);

            let mut stream = match stream_with_retry(
                &self.ctx.llm,
                request.clone(),
                self.ctx.max_retries,
                &self.ctx.hooks,
            )
            .await
            {
                Ok(s) => s,
                Err(e) => {
                    if let Some(ref tx) = tx {
                        let _ = tx.send(AgentEvent::RunFailed {
                            error: e.to_string(),
                        });
                    }
                    for hook in &self.ctx.hooks {
                        hook.on_run_finish(
                            "default",
                            &RunOutcome::Error {
                                error: e.to_string(),
                            },
                        );
                    }
                    if let Some(ref tx) = tx {
                        let _ = tx.send(AgentEvent::Done);
                    }
                    return Err(e);
                }
            };

            let mut acc = StreamAccumulator::new();

            while let Some(chunk_result) = stream.next().await {
                let chunk = match chunk_result {
                    Ok(c) => c,
                    Err(e) => {
                        let agent_err = AgentError::Provider(e);
                        if let Some(ref tx) = tx {
                            let _ = tx.send(AgentEvent::RunFailed {
                                error: agent_err.to_string(),
                            });
                        }
                        for hook in &self.ctx.hooks {
                            hook.on_run_finish(
                                "default",
                                &RunOutcome::Error {
                                    error: agent_err.to_string(),
                                },
                            );
                        }
                        if let Some(ref tx) = tx {
                            let _ = tx.send(AgentEvent::Done);
                        }
                        return Err(agent_err);
                    }
                };

                if let Some(ref tx) = tx {
                    emit_chunk_events(tx, &chunk, &mut acc);
                } else {
                    acc.ingest(&chunk);
                }
            }

            let assistant_msg = acc.into_assistant_message();

            for hook in &self.ctx.hooks {
                hook.on_llm_end("default", &assistant_msg);
            }

            if let Some(tool_calls) = &assistant_msg.tool_calls {
                if tool_calls.is_empty() {
                    if let Some(ref tx) = tx {
                        let _ = tx.send(AgentEvent::RunCompleted {
                            answer: assistant_msg.content.clone(),
                        });
                    }
                    for hook in &self.ctx.hooks {
                        hook.on_run_finish(
                            "default",
                            &RunOutcome::Success {
                                answer: assistant_msg.content.clone(),
                            },
                        );
                    }
                    if let Some(ref tx) = tx {
                        let _ = tx.send(AgentEvent::Done);
                    }
                    return Ok(assistant_msg.content);
                }

                // Emit complete tool-call events to the UI before execution begins.
                if let Some(ref tx) = tx {
                    for tc in tool_calls {
                        let _ = tx.send(AgentEvent::ToolCall {
                            id: tc.id.clone(),
                            name: tc.function.name.clone(),
                            arguments: tc.function.arguments.clone(),
                            origin: CallOrigin::Llm,
                        });
                    }
                }

                {
                    let mut mem = self.ctx.memory.write().unwrap();
                    mem.push(assistant_msg.clone());
                }

                for tc in tool_calls {
                    let mut blocked = false;
                    for hook in &self.ctx.hooks {
                        if let Err(e) = hook.before_tool_call("default", tc) {
                            let msg = Message::tool_result(&tc.id, format!("Tool rejected: {e}"));
                            {
                                let mut mem = self.ctx.memory.write().unwrap();
                                mem.push(msg);
                            }
                            if let Some(ref tx) = tx {
                                let _ = tx.send(AgentEvent::ToolResult {
                                    id: tc.id.clone(),
                                    name: tc.function.name.clone(),
                                    output: format!("[rejected] {e}"),
                                });
                            }
                            blocked = true;
                            break;
                        }
                    }

                    if blocked {
                        continue;
                    }

                    // ── Pull from progress stream ────────────────────
                    let tool_result = self
                        .ctx
                        .tools
                        .execute_stream(&tc.function.name, &tc.function.arguments);

                    let _observation = match tool_result {
                        Some(Ok(mut stream)) => {
                            let mut final_output = String::new();
                            while let Some(progress) = stream.next().await {
                                match progress {
                                    Progress::InProgress(msg) => {
                                        if let Some(ref tx) = tx {
                                            let _ = tx.send(AgentEvent::ToolProgress {
                                                id: tc.id.clone(),
                                                name: tc.function.name.clone(),
                                                message: msg,
                                            });
                                        }
                                    }
                                    Progress::Done(output) => final_output = output,
                                }
                            }
                            // Success path: notify hooks, push to memory, emit ToolResult.
                            for hook in &self.ctx.hooks {
                                hook.after_tool_call("default", tc, &final_output);
                            }
                            {
                                let mut mem = self.ctx.memory.write().unwrap();
                                mem.push(Message::tool_result(&tc.id, &final_output));
                            }
                            if let Some(ref tx) = tx {
                                let _ = tx.send(AgentEvent::ToolResult {
                                    id: tc.id.clone(),
                                    name: tc.function.name.clone(),
                                    output: final_output.clone(),
                                });
                            }
                            final_output
                        }
                        Some(Err(e)) => {
                            let err_msg = e.to_string();
                            for hook in &self.ctx.hooks {
                                hook.on_tool_failed("default", tc, &err_msg);
                            }
                            {
                                let mut mem = self.ctx.memory.write().unwrap();
                                mem.push(Message::tool_result(&tc.id, &err_msg));
                            }
                            if let Some(ref tx) = tx {
                                let _ = tx.send(AgentEvent::ToolFailure {
                                    id: tc.id.clone(),
                                    name: tc.function.name.clone(),
                                    error: err_msg.clone(),
                                });
                            }
                            err_msg
                        }
                        None => {
                            let err_msg = format!("Tool not found: {}", tc.function.name);
                            for hook in &self.ctx.hooks {
                                hook.on_tool_failed("default", tc, &err_msg);
                            }
                            {
                                let mut mem = self.ctx.memory.write().unwrap();
                                mem.push(Message::tool_result(&tc.id, &err_msg));
                            }
                            if let Some(ref tx) = tx {
                                let _ = tx.send(AgentEvent::ToolFailure {
                                    id: tc.id.clone(),
                                    name: tc.function.name.clone(),
                                    error: err_msg.clone(),
                                });
                            }
                            err_msg
                        }
                    };
                }
            } else {
                {
                    let mut mem = self.ctx.memory.write().unwrap();
                    mem.push(assistant_msg.clone());
                }
                if let Some(ref tx) = tx {
                    let _ = tx.send(AgentEvent::RunCompleted {
                        answer: assistant_msg.content.clone(),
                    });
                }
                for hook in &self.ctx.hooks {
                    hook.on_run_finish(
                        "default",
                        &RunOutcome::Success {
                            answer: assistant_msg.content.clone(),
                        },
                    );
                }
                if let Some(ref tx) = tx {
                    let _ = tx.send(AgentEvent::Done);
                }
                return Ok(assistant_msg.content);
            }
        }
    }

    async fn run_non_streaming_loop(
        &self,
        user_input: &str,
        tx: Option<mpsc::UnboundedSender<AgentEvent>>,
    ) -> Result<String, AgentError> {
        for hook in &self.ctx.hooks {
            hook.on_run_start("default", user_input);
        }

        // Notify the application that a run has started.
        if let Some(ref tx) = tx {
            let _ = tx.send(AgentEvent::RunStarted {
                session_id: "default".into(),
                user_input: user_input.to_string(),
            });
        }

        let mut steps = 0;
        loop {
            if steps >= self.ctx.max_steps {
                let err = AgentError::MaxStepsReached(self.ctx.max_steps);
                if let Some(ref tx) = tx {
                    let _ = tx.send(AgentEvent::RunFailed {
                        error: err.to_string(),
                    });
                }
                for hook in &self.ctx.hooks {
                    hook.on_run_finish(
                        "default",
                        &RunOutcome::Error {
                            error: err.to_string(),
                        },
                    );
                }
                if let Some(ref tx) = tx {
                    let _ = tx.send(AgentEvent::Done);
                }
                return Err(err);
            }
            steps += 1;

            // Step-level hooks — called before on_llm_start each iteration.
            for hook in &self.ctx.hooks {
                hook.on_step_start("default", steps, self.ctx.max_steps);
            }

            // Run pre-LLM hooks (compaction, etc.).
            for hook in &self.ctx.hooks {
                hook.on_llm_start("default", &self.ctx.memory);
            }

            let messages = {
                let mem = self.ctx.memory.read().unwrap();
                mem.to_context_vec()
            };

            let tools = self.ctx.tools.to_tool_defs();
            let request = CompletionRequest::new(&self.ctx.model, messages)
                .with_stream(false)
                .with_tools(tools);

            let response = match generate_with_retry(
                &self.ctx.llm,
                request,
                self.ctx.max_retries,
                &self.ctx.hooks,
            )
            .await
            {
                Ok(r) => r,
                Err(e) => {
                    if let Some(ref tx) = tx {
                        let _ = tx.send(AgentEvent::RunFailed {
                            error: e.to_string(),
                        });
                    }
                    for hook in &self.ctx.hooks {
                        hook.on_run_finish(
                            "default",
                            &RunOutcome::Error {
                                error: e.to_string(),
                            },
                        );
                    }
                    if let Some(ref tx) = tx {
                        let _ = tx.send(AgentEvent::Done);
                    }
                    return Err(e);
                }
            };

            let choice = match response.choices.into_iter().next() {
                Some(c) => c,
                None => {
                    let err = AgentError::NoChoices;
                    if let Some(ref tx) = tx {
                        let _ = tx.send(AgentEvent::RunFailed {
                            error: err.to_string(),
                        });
                    }
                    for hook in &self.ctx.hooks {
                        hook.on_run_finish(
                            "default",
                            &RunOutcome::Error {
                                error: err.to_string(),
                            },
                        );
                    }
                    if let Some(ref tx) = tx {
                        let _ = tx.send(AgentEvent::Done);
                    }
                    return Err(err);
                }
            };
            let content = choice.message.content.unwrap_or_default();
            let tool_calls = choice.message.tool_calls;
            let reasoning = choice.message.reasoning_content;

            let msg = Message {
                role: Role::Assistant,
                content: content.clone(),
                tool_calls: tool_calls.clone(),
                tool_call_id: None,
                name: None,
            };

            for hook in &self.ctx.hooks {
                hook.on_llm_end("default", &msg);
            }

            if let Some(ref tx) = tx {
                if let Some(ref r) = reasoning {
                    if !r.is_empty() {
                        let _ = tx.send(AgentEvent::ReasoningToken(r.clone()));
                    }
                }
                let _ = tx.send(AgentEvent::Token(content.clone()));
            }

            if let Some(tool_calls) = tool_calls {
                if tool_calls.is_empty() {
                    if let Some(ref tx) = tx {
                        let _ = tx.send(AgentEvent::RunCompleted {
                            answer: content.clone(),
                        });
                    }
                    for hook in &self.ctx.hooks {
                        hook.on_run_finish(
                            "default",
                            &RunOutcome::Success {
                                answer: content.clone(),
                            },
                        );
                    }
                    if let Some(ref tx) = tx {
                        let _ = tx.send(AgentEvent::Done);
                    }
                    {
                        let mut mem = self.ctx.memory.write().unwrap();
                        mem.push(msg);
                    }
                    return Ok(content);
                }

                {
                    let mut mem = self.ctx.memory.write().unwrap();
                    mem.push(msg);
                }

                for tc in &tool_calls {
                    let mut blocked = false;
                    for hook in &self.ctx.hooks {
                        if let Err(e) = hook.before_tool_call("default", tc) {
                            let tool_msg =
                                Message::tool_result(&tc.id, format!("Tool rejected: {e}"));
                            {
                                let mut mem = self.ctx.memory.write().unwrap();
                                mem.push(tool_msg);
                            }
                            blocked = true;
                            break;
                        }
                    }
                    if blocked {
                        continue;
                    }

                    // ── Pull from progress stream ────────────────────
                    let tool_result = self
                        .ctx
                        .tools
                        .execute_stream(&tc.function.name, &tc.function.arguments);

                    match tool_result {
                        Some(Ok(mut stream)) => {
                            let mut final_output = String::new();
                            while let Some(progress) = stream.next().await {
                                match progress {
                                    Progress::InProgress(msg) => {
                                        if let Some(ref tx) = tx {
                                            let _ = tx.send(AgentEvent::ToolProgress {
                                                id: tc.id.clone(),
                                                name: tc.function.name.clone(),
                                                message: msg,
                                            });
                                        }
                                    }
                                    Progress::Done(output) => final_output = output,
                                }
                            }
                            for hook in &self.ctx.hooks {
                                hook.after_tool_call("default", tc, &final_output);
                            }
                            {
                                let mut mem = self.ctx.memory.write().unwrap();
                                mem.push(Message::tool_result(&tc.id, &final_output));
                            }
                        }
                        Some(Err(e)) => {
                            let err_msg = e.to_string();
                            for hook in &self.ctx.hooks {
                                hook.on_tool_failed("default", tc, &err_msg);
                            }
                            {
                                let mut mem = self.ctx.memory.write().unwrap();
                                mem.push(Message::tool_result(&tc.id, &err_msg));
                            }
                            if let Some(ref tx) = tx {
                                let _ = tx.send(AgentEvent::ToolFailure {
                                    id: tc.id.clone(),
                                    name: tc.function.name.clone(),
                                    error: err_msg,
                                });
                            }
                        }
                        None => {
                            let err_msg = format!("Tool not found: {}", tc.function.name);
                            for hook in &self.ctx.hooks {
                                hook.on_tool_failed("default", tc, &err_msg);
                            }
                            {
                                let mut mem = self.ctx.memory.write().unwrap();
                                mem.push(Message::tool_result(&tc.id, &err_msg));
                            }
                            if let Some(ref tx) = tx {
                                let _ = tx.send(AgentEvent::ToolFailure {
                                    id: tc.id.clone(),
                                    name: tc.function.name.clone(),
                                    error: err_msg,
                                });
                            }
                        }
                    }
                }
            } else {
                if let Some(ref tx) = tx {
                    let _ = tx.send(AgentEvent::RunCompleted {
                        answer: content.clone(),
                    });
                }
                for hook in &self.ctx.hooks {
                    hook.on_run_finish(
                        "default",
                        &RunOutcome::Success {
                            answer: content.clone(),
                        },
                    );
                }
                if let Some(ref tx) = tx {
                    let _ = tx.send(AgentEvent::Done);
                }
                {
                    let mut mem = self.ctx.memory.write().unwrap();
                    mem.push(msg);
                }
                return Ok(content);
            }
        }
    }
}

// ── StreamAccumulator ─────────────────────────────────────────────────────────

// ── StreamAccumulator ─────────────────────────────────────────────────────────

struct StreamAccumulator {
    content: String,
    reasoning: String,
    tool_calls: BTreeMap<u32, ToolCallAccumulator>,
}

struct ToolCallAccumulator {
    id: String,
    name: String,
    arguments: String,
}

impl StreamAccumulator {
    fn new() -> Self {
        Self {
            content: String::new(),
            reasoning: String::new(),
            tool_calls: BTreeMap::new(),
        }
    }

    fn ingest(&mut self, chunk: &StreamChunk) {
        for choice in &chunk.choices {
            if let Some(ref c) = choice.delta.content {
                self.content.push_str(c);
            }
            if let Some(ref r) = choice.delta.reasoning_content {
                self.reasoning.push_str(r);
            }
            if let Some(ref tool_calls) = choice.delta.tool_calls {
                for tc in tool_calls {
                    let entry =
                        self.tool_calls
                            .entry(tc.index)
                            .or_insert_with(|| ToolCallAccumulator {
                                id: tc.id.clone(),
                                name: String::new(),
                                arguments: String::new(),
                            });
                    if !tc.id.is_empty() {
                        entry.id = tc.id.clone();
                    }
                    if !tc.function.name.is_empty() {
                        entry.name = tc.function.name.clone();
                    }
                    entry.arguments.push_str(&tc.function.arguments);
                }
            }
        }
    }

    fn into_assistant_message(self) -> Message {
        let tool_calls: Vec<ToolCall> = self
            .tool_calls
            .into_values()
            .map(|acc| ToolCall {
                index: 0,
                id: acc.id,
                r#type: ToolCallType::Function,
                function: ToolCallFunction {
                    name: acc.name,
                    arguments: acc.arguments,
                },
            })
            .collect();

        let tool_calls = if tool_calls.is_empty() {
            None
        } else {
            Some(tool_calls)
        };

        Message {
            role: Role::Assistant,
            content: self.content,
            tool_calls,
            tool_call_id: None,
            name: None,
        }
    }
}

// ── Event emission ────────────────────────────────────────────────────────────

fn emit_chunk_events(
    tx: &mpsc::UnboundedSender<AgentEvent>,
    chunk: &StreamChunk,
    acc: &mut StreamAccumulator,
) {
    for choice in &chunk.choices {
        if let Some(ref c) = choice.delta.content {
            let _ = tx.send(AgentEvent::Token(c.clone()));
        }
        if let Some(ref r) = choice.delta.reasoning_content {
            let _ = tx.send(AgentEvent::ReasoningToken(r.clone()));
        }
    }
    acc.ingest(chunk);
}

// ── Retry helpers ─────────────────────────────────────────────────────────────

async fn generate_with_retry(
    client: &impl LLMClient,
    request: CompletionRequest,
    max_retries: usize,
    hooks: &[Box<dyn AgentHook>],
) -> Result<CompletionResponse, AgentError> {
    let mut last_err = None;
    for attempt in 0..=max_retries {
        if attempt > 0 {
            let backoff = Duration::from_millis(500 * 2u64.pow(attempt as u32 - 1));
            tokio::time::sleep(backoff).await;
        }
        match client.generate(request.clone()).await {
            Ok(resp) => return Ok(resp),
            Err(e) => {
                let will_retry = is_retryable(&e) && attempt < max_retries;
                for hook in hooks {
                    hook.on_llm_error("default", &e, attempt, will_retry);
                }
                if !is_retryable(&e) {
                    return Err(AgentError::Provider(e));
                }
                last_err = Some(e);
            }
        }
    }
    Err(AgentError::Provider(last_err.unwrap()))
}

async fn stream_with_retry(
    client: &impl LLMClient,
    request: CompletionRequest,
    max_retries: usize,
    hooks: &[Box<dyn AgentHook>],
) -> Result<futures_util::stream::BoxStream<'static, Result<StreamChunk, ProviderError>>, AgentError>
{
    let mut last_err = None;
    for attempt in 0..=max_retries {
        if attempt > 0 {
            let backoff = Duration::from_millis(500 * 2u64.pow(attempt as u32 - 1));
            tokio::time::sleep(backoff).await;
        }
        match client.stream(request.clone()).await {
            Ok(stream) => return Ok(stream),
            Err(e) => {
                let will_retry = is_retryable(&e) && attempt < max_retries;
                for hook in hooks {
                    hook.on_llm_error("default", &e, attempt, will_retry);
                }
                if !is_retryable(&e) {
                    return Err(AgentError::Provider(e));
                }
                last_err = Some(e);
            }
        }
    }
    Err(AgentError::Provider(last_err.unwrap()))
}

fn is_retryable(err: &ProviderError) -> bool {
    match err {
        ProviderError::Http(_) => true,
        ProviderError::Api { status, .. } => status >= &500u16,
        ProviderError::Parse(_) => false,
        ProviderError::StreamingNotSupported => false,
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_stream_accumulator_text_only() {
        let mut acc = StreamAccumulator::new();
        let chunk: StreamChunk = serde_json::from_str(
            r#"{"id":"1","object":"c","created":1,"model":"m","choices":[{"index":0,"delta":{"content":"Hello"},"finish_reason":null}],"usage":null}"#,
        )
        .unwrap();
        acc.ingest(&chunk);
        let msg = acc.into_assistant_message();
        assert_eq!(msg.content, "Hello");
        assert!(msg.tool_calls.is_none());
    }

    #[test]
    fn test_agent_error_display() {
        assert!(AgentError::MaxStepsReached(10).to_string().contains("10"));
        assert!(AgentError::NoOutput.to_string().contains("empty"));
    }

    #[test]
    fn test_is_retryable() {
        assert!(is_retryable(&ProviderError::Http("timeout".into())));
        assert!(is_retryable(&ProviderError::Api {
            status: 503,
            body: "".into()
        }));
        assert!(!is_retryable(&ProviderError::Api {
            status: 400,
            body: "".into()
        }));
        assert!(!is_retryable(&ProviderError::Parse("oops".into())));
    }
}
