[package]
name = "observability"
version.workspace = true
edition = "2024"

[dependencies]
tracing = { workspace = true }
provider = { version = "0.5.0", path = "../../core/provider" }
engine = { version = "0.5.0", path = "../../core/engine" }
memory = { version = "0.5.0", path = "../../core/memory" }
